server {
    listen       8080;
    server_name  _;

    root /usr/share/nginx/html;

    location /inbox/ {
        try_files $uri $uri/ /inbox/index.html;
    }

    location /calendar/ {
        try_files $uri $uri/ /calendar/index.html;
    }

    location /stone-calendar/ {
        try_files $uri $uri/ /stone-calendar/index.html;
    }

    location /address/ {
        try_files $uri =404;
    }

    location /stage-summary/ {
        try_files $uri =404;
    }

    location = / {
        return 204;
    }
}
